# Generated by Django 5.2.6 on 2025-12-03 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_companion_alter_patient_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companion',
            options={'verbose_name': 'Acompanhante', 'verbose_name_plural': 'Acompanhantes'},
        ),
    ]
