# Generated by Django 5.2.6 on 2026-02-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_card_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(blank=True, choices=[(0, 'Admin'), (1, 'Motorista'), (2, 'Monitor'), (3, 'Paciente')], max_length=10, null=True, verbose_name='Tipo de Usuário'),
        ),
    ]
