# Generated by Django 5.2.6 on 2026-02-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Motorista'), (2, 'Monitor'), (3, 'Paciente')], default=3, verbose_name='Tipo de Usuário'),
        ),
    ]
