# Generated by Django 6.0.3 on 2026-03-18 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_vitalmonitordevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='companion',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.address', verbose_name='Endereço'),
        ),
    ]
