# Generated by Django 6.0.3 on 2026-03-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_companion_user_alter_patient_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='complement',
            field=models.CharField(blank=True, max_length=128, verbose_name='Complemento'),
        ),
    ]
