# Generated by Django 5.2.6 on 2026-01-29 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_companion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuários', 'verbose_name_plural': 'Usuários'},
        ),
    ]
