# Generated by Django 5.2.6 on 2026-02-03 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='patient',
        ),
    ]
