# Generated by Django 6.0.3 on 2026-03-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalMonitorDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True, verbose_name='Identificador Universal')),
                ('in_use', models.BooleanField(default=False, verbose_name='Em Uso')),
            ],
            options={
                'verbose_name': 'Dispositivo de Monitoração de Sinais Vitais',
                'verbose_name_plural': 'Dispositivos de Monitoração de Sinais Vitais',
            },
        ),
    ]
