# Generated by Django 6.0.3 on 2026-03-13 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0011_vitalmonitordevice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier_code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Identificador"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ônibus",
                "verbose_name_plural": "Caravana",
            },
        ),
        migrations.CreateModel(
            name="Destiny",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destiny", models.CharField(max_length=64)),
            ],
            options={
                "verbose_name": "Destino",
                "verbose_name_plural": "Destinos",
            },
        ),
        migrations.CreateModel(
            name="Travel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vacations",
                    models.IntegerField(default=31, verbose_name="Vagas para viagem"),
                ),
                ("date", models.DateField(verbose_name="Data da Viagem")),
                ("time", models.TimeField(verbose_name="Hora da Viagem")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Pendente"), (1, "Andamento"), (2, "Concluída")],
                        default=0,
                        verbose_name="Status da Viagem",
                    ),
                ),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="travels.bus",
                        verbose_name="Ônibus",
                    ),
                ),
                (
                    "destiny",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="travels.destiny",
                        verbose_name="Destino",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_driver",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Motorista",
                    ),
                ),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_monitor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Monitor",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_owner",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Viagem",
                "verbose_name_plural": "Viagens",
            },
        ),
        migrations.CreateModel(
            name="TravelBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "need_vital_monitor_device",
                    models.BooleanField(
                        default=False, verbose_name="Paciente precisa de monitoramento?"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data do Agendamento"
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        auto_now_add=True, verbose_name="Hora do Agendamento"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Pendente"), (1, "Cancelado"), (2, "Confirmado")],
                        default=0,
                        verbose_name="Status da Solicitação",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="users.card",
                        verbose_name="Cartão do usuário",
                    ),
                ),
                (
                    "companion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="users.companion",
                        verbose_name="Acompanhante",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.patient",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "travel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="travels.travel",
                        verbose_name="Viagem",
                    ),
                ),
                (
                    "vital_monitor_device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="users.vitalmonitordevice",
                        verbose_name="Dispositivo de Monitoramento do usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação",
                "verbose_name_plural": "Solicitações",
            },
        ),
        migrations.CreateModel(
            name="BoardingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "on_board",
                    models.BooleanField(default=False, verbose_name="Embarcado"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="users.card",
                        verbose_name="Cartão",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="users.patient",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="travels.bus"
                    ),
                ),
                (
                    "travel_booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="travels.travelbooking",
                        verbose_name="Solicitação de Viagem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Embarque",
                "verbose_name_plural": "Registros de Embarque",
            },
        ),
    ]
