# Generated by Django 5.2.6 on 2025-10-30 14:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardingrecord',
            options={'get_latest_by': 'created_at', 'verbose_name': 'Associação de Cartão ao Agendamento', 'verbose_name_plural': 'Associações de Cartões aos Agendamentos'},
        ),
        migrations.RemoveField(
            model_name='boardingrecord',
            name='date',
        ),
        migrations.RemoveField(
            model_name='boardingrecord',
            name='time',
        ),
        migrations.AddField(
            model_name='boardingrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardingrecord',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='users.patient', verbose_name='Paciente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boardingrecord',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='travels.bus'),
        ),
        migrations.AlterField(
            model_name='boardingrecord',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.card', verbose_name='Cartão'),
        ),
    ]
