# Generated by Django 5.2.6 on 2025-10-30 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_alter_boardingrecord_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name': 'Ônibus', 'verbose_name_plural': 'Caravana'},
        ),
        migrations.AddField(
            model_name='bus',
            name='identifier_code',
            field=models.CharField(default='', max_length=100, verbose_name='Identificador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bus',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_driver', to=settings.AUTH_USER_MODEL, verbose_name='Motorista'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='monitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_monitor', to=settings.AUTH_USER_MODEL, verbose_name='Monitor'),
        ),
    ]
