# Generated by Django 5.2.6 on 2025-10-30 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_alter_bus_options_bus_identifier_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_driver', to=settings.AUTH_USER_MODEL, verbose_name='Motorista'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_monitor', to=settings.AUTH_USER_MODEL, verbose_name='Monitor'),
        ),
    ]
