# Generated by Django 5.2.6 on 2025-11-26 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0005_alter_bus_driver_alter_bus_monitor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardingrecord',
            options={'verbose_name': 'Associação de Cartão ao Agendamento', 'verbose_name_plural': 'Associações de Cartões aos Agendamentos'},
        ),
        migrations.AddField(
            model_name='travel',
            name='vacations',
            field=models.IntegerField(default=31, verbose_name='Vagas para viagem'),
        ),
        migrations.AddField(
            model_name='travelbooking',
            name='companion',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelbooking',
            name='quant_companion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_driver', to=settings.AUTH_USER_MODEL, verbose_name='Motorista Atual'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_monitor', to=settings.AUTH_USER_MODEL, verbose_name='Monitor Atual'),
        ),
    ]
