# Generated by Django 5.2.6 on 2025-11-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0006_alter_boardingrecord_options_travel_vacations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardingrecord',
            name='patient',
        ),
    ]
