# Generated by Django 5.2.6 on 2025-11-26 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0007_remove_boardingrecord_patient'),
        ('users', '0002_alter_card_options_alter_card_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardingrecord',
            name='patient',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='users.patient', verbose_name='Paciente'),
            preserve_default=False,
        ),
    ]
