# Generated by Django 5.2.6 on 2025-12-03 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0008_boardingrecord_patient'),
        ('users', '0003_companion_alter_patient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelbooking',
            name='quant_companion',
        ),
        migrations.AddField(
            model_name='travel',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Andamento', 'Andamento'), ('Concluída', 'Concluída')], default='Pendente', max_length=10, verbose_name='Status da Viagem'),
        ),
        migrations.AlterField(
            model_name='travelbooking',
            name='companion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.companion', verbose_name='Acompanhante'),
        ),
    ]
