# Generated by Django 5.2.6 on 2025-12-03 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0010_destiny_travel_destiny'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardingrecord',
            old_name='travel_patient',
            new_name='travel_booking',
        ),
        migrations.RemoveField(
            model_name='travelbooking',
            name='canceled',
        ),
        migrations.RemoveField(
            model_name='travelbooking',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='travelbooking',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada')], default='Pendente', max_length=10, verbose_name='Status da Solicitação'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='destiny',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='travels.destiny', verbose_name='Destino'),
        ),
    ]
