# Generated by Django 5.2.6 on 2025-12-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0011_rename_travel_patient_boardingrecord_travel_booking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='monitor',
        ),
    ]
