# Generated by Django 5.2.6 on 2026-02-03 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0017_alter_travelbooking_status'),
        ('users', '0007_remove_card_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelbooking',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.card', verbose_name='Cartão do usuário'),
        ),
    ]
