# Generated by Django 6.0.3 on 2026-03-11 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0018_travelbooking_card'),
        ('users', '0011_vitalmonitordevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelbooking',
            name='need_vital_monitor_device',
            field=models.BooleanField(default=False, verbose_name='Paciente precisa de monitoramento?'),
        ),
        migrations.AddField(
            model_name='travelbooking',
            name='vital_monitor_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.vitalmonitordevice', verbose_name='Dispositivo de Monitoramento do usuário'),
        ),
    ]
