# Generated by Django 5.2.6 on 2025-10-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data da Associação')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Hora da Associação')),
                ('on_board', models.BooleanField(default=False, verbose_name='Embarcado')),
            ],
            options={
                'verbose_name': 'Associação de Cartão ao Agendamento',
                'verbose_name_plural': 'Associações de Cartões aos Agendamentos',
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data da Viagem')),
                ('time', models.TimeField(verbose_name='Hora da Viagem')),
            ],
            options={
                'verbose_name': 'Viagem',
                'verbose_name_plural': 'Viagens',
            },
        ),
        migrations.CreateModel(
            name='TravelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data do Agendamento')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Hora do Agendamento')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Confirmação do Agendamento')),
                ('canceled', models.BooleanField(default=False, verbose_name='Cancelamento do Agendamento')),
            ],
            options={
                'verbose_name': 'Agendamento de Viagem do Paciente',
                'verbose_name_plural': 'Agendamentos de Viagens dos Pacientes',
            },
        ),
    ]
