# Generated by Django 5.2.6 on 2025-10-04 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travels', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boardingrecord',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.card', verbose_name='Cartão'),
        ),
        migrations.AddField(
            model_name='bus',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_driver', to=settings.AUTH_USER_MODEL, verbose_name='Motorista'),
        ),
        migrations.AddField(
            model_name='bus',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_monitor', to=settings.AUTH_USER_MODEL, verbose_name='Monitor'),
        ),
        migrations.AddField(
            model_name='boardingrecord',
            name='bus',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='travels.bus'),
        ),
        migrations.AddField(
            model_name='travel',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.bus', verbose_name='Ônibus'),
        ),
        migrations.AddField(
            model_name='travel',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_driver', to=settings.AUTH_USER_MODEL, verbose_name='Motorista'),
        ),
        migrations.AddField(
            model_name='travel',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_monitor', to=settings.AUTH_USER_MODEL, verbose_name='Monitor'),
        ),
        migrations.AddField(
            model_name='travel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_owner', to=settings.AUTH_USER_MODEL, verbose_name='Criador'),
        ),
        migrations.AddField(
            model_name='travelbooking',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='travelbooking',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.travel', verbose_name='Viagem'),
        ),
        migrations.AddField(
            model_name='boardingrecord',
            name='travel_patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='travels.travelbooking', verbose_name='Agendamento de Viagem do Paciente'),
        ),
    ]
