# Generated by Django 5.2.6 on 2025-12-04 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0012_remove_bus_driver_remove_bus_monitor'),
        ('users', '0004_alter_companion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelbooking',
            name='companion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.companion', verbose_name='Acompanhante'),
        ),
    ]
