# Generated by Django 5.2.6 on 2026-01-29 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0013_alter_travelbooking_companion'),
        ('users', '0004_alter_companion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardingrecord',
            options={'verbose_name': 'Registro de Embarque', 'verbose_name_plural': 'Registros de Embarque'},
        ),
        migrations.AlterModelOptions(
            name='travelbooking',
            options={'verbose_name': 'Solicitação', 'verbose_name_plural': 'Solicitações'},
        ),
        migrations.AlterField(
            model_name='boardingrecord',
            name='travel_booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='travels.travelbooking', verbose_name='Solicitação de Viagem'),
        ),
        migrations.AlterField(
            model_name='travelbooking',
            name='companion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.companion', verbose_name='Acompanhante'),
        ),
        migrations.AlterField(
            model_name='travelbooking',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=10, verbose_name='Status da Solicitação'),
        ),
    ]
