# Generated by Django 5.2.6 on 2026-01-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0014_alter_boardingrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='identifier_code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='status',
            field=models.CharField(choices=[(0, 'Pendente'), (1, 'Andamento'), (2, 'Concluída')], default=0, max_length=10, verbose_name='Status da Viagem'),
        ),
    ]
