# Generated by Django 5.2.6 on 2026-01-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0015_alter_bus_identifier_code_alter_travel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pendente'), (1, 'Andamento'), (2, 'Concluída')], default=0, verbose_name='Status da Viagem'),
        ),
        migrations.AlterField(
            model_name='travelbooking',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pendente'), (1, 'Andamento'), (2, 'Concluída')], default=0, verbose_name='Status da Solicitação'),
        ),
    ]
