# Generated by Django 5.2.6 on 2026-01-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0016_alter_travel_status_alter_travelbooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelbooking',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pendente'), (1, 'Cancelado'), (2, 'Confirmado')], default=0, verbose_name='Status da Solicitação'),
        ),
    ]
