# Generated by Django 6.0.3 on 2026-03-18 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0019_travelbooking_need_vital_monitor_device_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='destiny',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='monitor',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='travelbooking',
            name='travel',
        ),
        migrations.RemoveField(
            model_name='travelbooking',
            name='card',
        ),
        migrations.RemoveField(
            model_name='travelbooking',
            name='companion',
        ),
        migrations.RemoveField(
            model_name='travelbooking',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='travelbooking',
            name='vital_monitor_device',
        ),
        migrations.DeleteModel(
            name='BoardingRecord',
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.DeleteModel(
            name='Destiny',
        ),
        migrations.DeleteModel(
            name='Travel',
        ),
        migrations.DeleteModel(
            name='TravelBooking',
        ),
    ]
